"""rename_update_by_update_at_columns

Revision ID: 534afd522627
Revises: f8505b70fb4c
Create Date: 2026-05-03 13:06:31.057387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '534afd522627'
down_revision: Union[str, Sequence[str], None] = 'f8505b70fb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('prompts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('prompts_update_by_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'users', ['updated_by'], ['id'])
    op.drop_column('prompts', 'update_at')
    op.drop_column('prompts', 'update_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('update_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('prompts', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.create_foreign_key(op.f('prompts_update_by_fkey'), 'prompts', 'users', ['update_by'], ['id'])
    op.drop_column('prompts', 'updated_at')
    op.drop_column('prompts', 'updated_by')
    # ### end Alembic commands ###
